SUPABASE_URlL=jdbc:postgresql://db.ulasdclgwpkahcyifjqr.supabase.co:5432/postgres
SUPABASE_USER=postgres
SUPABASE_KEY = sb_secret_FDhaqbWSA1Obru00wGOBHA_WeNVrKGV
SUPABASE_PASSWORD=FiTrakApp123

SUPABASE_URL=https://ulasdclgwpkahcyifjqr.supabase.co
SUPABASE_APIKEY=sb_secret_FDhaqbWSA1Obru00wGOBHA_WeNVrKGV
SUPABASE_PROJECTREF=ulasdclgwpkahcyifjqr
SUPABASE_TABLE_ACCOUNTS=accounts
SUPABASE_TABLE_SYNCLOGS=syncLogs

# Local SQLite
SQLITE_DBURL=jdbc:sqlite:FitrakAccount.db

# Sync metadata
SERVER_ORIGIN=Client-JAM-PC-001
DATE_FORMAT=yyyy-MM-dd HH:mm
